//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsedCarSales
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public System.DateTime date { get; set; }
        public decimal totalCost { get; set; }
        public int Vehicle_id { get; set; }
        public int Customer_id { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
